### ISSUE TITLE
Is this regular Tello or Tello EDU?

### ISSUE THREAD

**Issue by lordbagel42** [PedroS235/TelloSwarm#2]
Description doesn’t say which, input would be great.

**Comment by PedroS235** [comment]
Hi @lordbagel42,

I have used DJI Tello, the regular ones. However, if I am being honest with you, this is repo is very outdated, actually. Therefore, I don't know if this will even work today. In case you just want to control your drone with ROS, I have made 2 packages, one for ROS1(no longer working on this one) and one for ROS2. 

I might be updating this package to work with the ROS driver I have developed, but that is not in my plans for the moment.

You can find them here: 
- [ROS1](https://github.com/PedroS235/tello_driver_ros_wrapper)
- [ROS2](https://github.com/PedroS235/tello_ros_wrapper)

**Comment by lordbagel42** [comment]
For any development purposes I was going to use a different driver, yes.

I do wonder, what was the “controllers” described in the documentation?
Were they custom or something you could buy? I couldn’t find any in for for it.

Thank you.

**Comment by PedroS235** [comment]
The controllers in my case were simply Raspberry Pi's, or the odroid xu4+ which are equivalent, which were all connected to a switch. But it is not required. In fact, an alternative would be to use a single pc, but with for example Wi-Fi dongles, one for each drone you plan on using. 

This said, a controller is basically a ROS node, that controls a drone.

**Comment by lordbagel42** [comment]
Thank you. I think I can make a couple virtual interfaces, or I do have a few USB WiFi dongles.
